// src/routes/HeaderBar.svelte
<style>
    #header {
        width: 100%;
        background-color: rgb(154, 51, 52);
        padding: 8px 16px;
        margin: 0;
        box-sizing: unset;
        height: 64px;
    }

    #header img {
        margin-top: 10px;
        float: left;
    }
    nav {
        display: block;
    }

    nav ul {
        list-style: none;
        list-style-image: none;
        margin: 0;
        padding: 0;
        float: right;
        padding-right: 16px;
    }

    nav li {
        float: left;
        clear: none;
    }

    nav a {
        display: block;
        padding: 1.5em 1em;
        height: 1em;
        text-align: center;
        font-size: 1em;
        font-family: "Open Sans", sans-serif;
        text-decoration: none;
        color: white;
    }

    nav a:hover,
    nav a:focus,
    nav a:active {
        color: #f1f1d4;
    }
</style>

<div id="header">
    <img src="https://wildfiregames.com/img/logo.png" alt="Wildfire Games" />
    <nav>
        <ul>
            <li><a href="https://www.play0ad.com/">0 A.D.</a></li>
            <li><a href="http://trac.wildfiregames.com/">Development</a></li>
            <li><a href="https://www.wildfiregames.com/forum/">Forums</a></li>
            <li><a href="https://www.wildfiregames.com/irc.html">Chat</a></li>
        </ul>
    </nav>
</div>

// src/components/HeaderBar.tsx
/**
 * SPDX-License-Identifier: GPL-3.0-or-later
 * SPDX-FileCopyrightText: © 2024 Stanislas Daniel Claude Dolcini
 */

import './HeaderBar.css'

const HeaderBar = function () : JSX.Element {
    return (
        <div id="header" className='select-none'>
            <a href="/"><img src="https://wildfiregames.com/img/logo.png" alt="Wildfire Games" /></a>
            <nav>
                <ul>
                    <li><a className='select-none' href="https://www.play0ad.com/">0 A.D.</a></li>
                    <li><a className='select-none' href="http://trac.wildfiregames.com/">Development</a></li>
                    <li><a className='select-none' href="https://www.wildfiregames.com/forum/">Forums</a></li>
                    <li><a className='select-none' href="https://www.wildfiregames.com/irc.html">Chat</a></li>
                </ul>
            </nav>
        </div>
    )
}

export {
    HeaderBar
}
