// src/routes/ReplayDetails/ReplayDetails.svelte
<script type="text/javascript">
  import { onMount } from "svelte";
	import PlayerStatistics from './PlayerStatistics.svelte'


  String.prototype.toHHMMSS = function () {
    var sec_num = parseInt(this, 10); // don't forget the second param
    var hours   = Math.floor(sec_num / 3600);
    var minutes = Math.floor((sec_num - (hours * 3600)) / 60);
    var seconds = sec_num - (hours * 3600) - (minutes * 60);

    if (hours   < 10) {hours   = "0"+hours;}
    if (minutes < 10) {minutes = "0"+minutes;}
    if (seconds < 10) {seconds = "0"+seconds;}
    return hours+':'+minutes+':'+seconds;
}

  export let replay = null;
  export let playerData = null;
  onMount(async () => {
      const urlParams = new URLSearchParams(window.location.search);
      const matchId = urlParams.get('matchId');
      const r = await fetch(`http://localhost:8080/replays/${matchId}`)
      const data = await r.json();
      replay = data;
      if(replay.metadata)
      {
        replay.previewImage = replay.metadata.mapPreview?.split(":")[2]
        const mode = (myArray) => myArray.reduce(      (a,b,i,arr)=>      (arr.filter(v=>v===a).length>=arr.filter(v=>v===b).length?a:b),null);
        playerData = replay.metadata.settings.PlayerData;
        for(const player of playerData)
          player.MostUsedCmd = mode(player.Commands.map(a => a.type));
        for(const player of playerData)
          player.SecondMostUsedCmd = mode(player.Commands.filter(a => a.type !== player.MostUsedCmd).map(a => a.type));

      }
    })
</script>
<div  id="wrapper">
  {#if replay}
  <h2><a href="../">Replay Pallàs</a> &gt; {replay.matchId}</h2>
  <h3><a href="../">General Match Info</h3>
  <div class="grid grid-cols-4">
     <div class="crop-container">
        <img width="256" src="https://cdn.jsdelivr.net/gh/0ad/0ad/binaries/data/mods/public/art/textures/ui/{replay.previewImage}" style="position: relative; max-width:none;" alt="map preview of {replay.metadata.settings.Name}" aria-hidden="true">
     </div>
     <article class="col-span-3 grid grid-cols-2">
      <small>
       Map Name: <b>{replay.metadata.settings.Name || replay.metadata.settings.mapName}</b>
        </small><br/>
      <small>
      Number of players: <b>{replay.metadata.settings.PlayerData.length}</b>
      </small><br/>
      <small>
        Match duration: <b>{(replay.metadata.settings.MatchDuration + "").toHHMMSS()}</b>
      </small><br/>
      <small>
        Date: <b>{new Date(replay.metadata.timestamp *1000).toLocaleDateString("en-GB",{
          year: "numeric",
          month: "2-digit",
          day: "2-digit"
    })}</b>
      </small><br/>
      <small>
        Pyrogenesis Version: <b>{replay.metadata.engine_version}</b>
      </small><br/>

    {#if replay.metadata.settings.Biome}
      <small>
        Biome: <b>{replay.metadata.settings.Biome}</b>
      </small><br/>
    {/if}
    {#if replay.metadata.settings.RatingEnabled}
      <small>
        Ranked: <b>{replay.metadata.settings.RatingEnabled}</b>
      </small><br/>
      {/if}
      <small>
        Teams Locked: <b>{replay.metadata.settings.LockTeams}</b>
      </small><br/>
      <small>
        Random Map Seed: <b>{replay.metadata.settings.Seed}</b>
      </small><br/>
      <small>
        Starting Resources: <b>{replay.metadata.settings.StartingResources}</b>
      </small><br/>
      <small>
        Population Cap: <b>{replay.metadata.settings.PopulationCap}</b>
      </small><br/>



    {#if replay.metadata.settings.Size}
      <small>
        Size: <b>{replay.metadata.settings.Size}</b>
      </small>
    {/if}
    </article>
  </div>
  {#if playerData}
    <PlayerStatistics {playerData} />
  {/if}
  {:else}
  <p class="loading">loading...</p>
  {/if}
</div>

<style>
.crop-container {
    width: 205px;
    height: 150px;
    overflow: hidden;
}
img {
  line-height: 0;
  text-indent: -999em;
}
img::after {
  content: "";
  display: block;
  background-color: white;
  background-image: url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/1255/image-not-found.svg");
  background-position: center;
  background-size: cover;
  padding: 50% 0;
  margin-left: -80px;
  position: relative;
}
</style>

// src/components/ReplayDetails.tsx
/**
 * SPDX-License-Identifier: GPL-3.0-or-later
 * SPDX-FileCopyrightText: © 2024 Stanislas Daniel Claude Dolcini
 */

import { Replay } from "../types/Replay";
import { useTranslation as translate } from "../contexts/Models/useTranslation";
import { toHHMMSS } from "../utils";
import axios from "axios";
import { useAuth } from "../contexts/Models/IAuthContext";
import { BlockTitle } from "./BlockTitle";

interface IReplayBlockProps {
    replay: Replay;
}

const ReplayDetails = (props: IReplayBlockProps): JSX.Element => {
    let replay: Replay = props.replay;
    const { token } = useAuth();

    const onClick = (event: React.MouseEvent<HTMLButtonElement>) => {
        event.preventDefault();
        axios.get(`http://localhost:8080/replays/${props.replay.match_id}/zip`, {
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${token}`,
            },
            responseType: 'blob'
        }
        )
            .then(({ data: blob }) => {
                const link = document.createElement('a');
                const url = URL.createObjectURL(blob);
                link.href = url;
                link.download = `${props.replay.match_id}.zip`;
                link.click();
            });
    }

    return (<>
        <div id="replay-detail-container" className="text-sm p-6 bg-white shadow-md" style={{ border: "1px solid", borderRadius: "4px" }}>
            <BlockTitle titleKey="ReplayDetails.Title" />
            <article className="font-sans">
                <div className=" grid grid-cols-4">
                    <div className="crop-container w-[256px] h-[150px} max-h-[256px] bg-black overflow-hidden">
                        <img
                            className="ml-[9%] mt-[20%] mb-[20%] w-[256px] h-[150px}"
                            src={`https://cdn.jsdelivr.net/gh/0ad/0ad/binaries/data/mods/public/art/textures/ui/${replay.metadata.previewImage}`}
                            style={{
                                position: "relative",
                                maxWidth: "none"
                            }}
                            alt={`map preview of ${replay.metadata.settings.Name}`}
                            aria-hidden="true"
                        />
                    </div>
                    <div className="grid grid-cols-2 p-5 col-span-3">
                        <span className="text-sm">
                            {translate("ReplayDetails.MapName")} <b
                            >{replay.metadata.settings.Name ||
                                replay.metadata.settings.mapName}</b>
                        </span>
                        <span className="text-sm">
                            {translate("ReplayDetails.PlayerCount")}  <b
                            >{replay.metadata.settings.PlayerData.length}</b>
                        </span>
                        <span className="text-sm">
                            {translate("ReplayDetails.MatchDuration")}  <b>{toHHMMSS(replay.metadata.settings.MatchDuration + "")}</b            >
                        </span>
                        <span className="text-sm">
                            {translate("ReplayDetails.Date")} <b >{new Date(replay.metadata.timestamp * 1000).toLocaleDateString(
                                "en-GB",
                                {
                                    year: "numeric",
                                    month: "2-digit",
                                    day: "2-digit",
                                }
                            )}</b>
                        </span>
                        <span className="text-sm">
                            {translate("ReplayDetails.PyrogenesisVersion")} <b>{replay.metadata.engine_version}</b>
                        </span>
                        {
                            replay.metadata.settings.Biome ?
                                <>
                                    <span className="text-sm">
                                        {translate("ReplayDetails.Biome")} <b>{replay.metadata.settings.Biome}</b>
                                    </span>

                                </> :
                                null
                        }
                        {
                            replay.metadata.settings.RatingEnabled ? <>
                                <span className="text-sm">
                                    {translate("ReplayDetails.Ranked")} <b>{replay.metadata.settings.RatingEnabled.toString()}</b>
                                </span></> :
                                null
                        }
                        {
                            replay.metadata.settings.LockTeams !== undefined ? <>
                                <span className="text-sm">
                                    {translate("ReplayDetails.Ranked")} <b>{replay.metadata.settings.LockTeams.toString()}</b>
                                </span></> :
                                null
                        }
                        <span className="text-sm">
                            {translate("ReplayDetails.RandomMapSeed")} : <b>{replay.metadata.settings.Seed}</b>
                        </span>
                        <span className="text-sm">
                            {translate("ReplayDetails.StartingResources")}<b>{replay.metadata.settings.StartingResources}</b>
                        </span>
                        <span className="text-sm">
                            {translate("ReplayDetails.PopulationCap")} <b>{replay.metadata.settings.PopulationCap}</b>
                        </span>
                        {
                            replay.metadata.settings.Size ?
                                <span className="text-sm">
                                    {translate("ReplayDetails.Size")} <b>{replay.metadata.settings.Size}</b>
                                </span> : null
                        }<br />
                        <div>
                            {
                                replay.metadata.mods ?
                                    <span className="text-sm">
                                        {translate("ReplayDetails.Mods")}&nbsp;{
                                            replay.metadata.mods?.map(a => <span><b>{a.name}</b> ({a.version}),&nbsp;</span>)
                                        }
                                    </span> : ""
                            }
                        </div>
                    </div>
                    <center className="col-span-3">
                        <div className="pt-2">
                            <button onClick={onClick} className="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded inline-flex items-center">
                                <svg className="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M19 9h-4V3H9v6H5l7 7zM5 18v2h14v-2z" /></svg>
                                <span>{translate("ReplayDetails.Download")}</span>
                            </button>
                        </div>
                    </center>
                </div>
            </article>
        </div>
    </>)
}

export {
    ReplayDetails
}
